version: "3.8"

services:
    php:
        build:
            context: .
            dockerfile: docker/Php.Dockerfile
        container_name: php_gorod
        restart: always
        working_dir: /var/www/app
        volumes:
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./:/var/www/app
        links:
            - mysql
    nginx:
        image: nginx
        container_name: nginx_gorod
        restart: always
        ports:
            - "8885:80"
        working_dir: /var/www/app
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
            - ./:/var/www/app
        links:
            - php
    mysql:
        image: mariadb:10.7.1
        container_name: mysql_gorod
        restart: always
        ports:
            - "33063:3306"
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=gorod_pomnit
        volumes:
            - ./db-data:/var/lib/mysql/
